<a href="https://colab.research.google.com/github/Vijay200417/Vijay200417/blob/main/Copy_of_python_(4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is Python?
- High-level, interpreted language known for its simplicity and readability.<br>
### Key Features:
- Open-source, extensive libraries, cross-platform.

### print statement

In [ ]:
print("Welcome to AI class")

Welcome to AI class


<h5>Variables are like a box that can store items</h5>
Name of variables<br>
<ol>
<li>should start with a alphabet or underscore</li>
<li>Its case sensitive eg: A and a are different </li>
<li>should not start with numbers</li>
<li>should not be a inbuilt keyword in python eg:if,else,for </li>
<li>variable name can contain A-Z,a-z,0-9,_
</li></ol>

<img src="https://th.bing.com/th/id/R.6e5900d22fd23a35661275c72190f792?rik=n8pOybuyd7iQTg&riu=http%3a%2f%2finventwithpython.com%2fhacking%2fchapter3_files%2fimage007.jpg&ehk=Bmd86viGYlFBvKZyCWyf3D4CS%2f3iyCorWXfZYpuTLTY%3d&risl=&pid=ImgRaw&r=0">

In [ ]:
fruit= "apple"
quantity=3
cost_price,selling_price=20,30
item=colour="orange"
print("the fruit is",fruit,"the quantity is",quantity,"cost price",cost_price,"selling_price",selling_price,"item",item,"colour",colour)

the fruit is apple the quantity is 3 cost price 20 selling_price 30 item orange colour orange


### INPUT STATEMENT
It is used to get the value from user during the run time

In [ ]:
name=input("enter your name:")
Class=input("enter your class:")
#Class and class are different in python cause of case sensitive
#class=input("enter your class:")

enter your name: lisa
enter your class: 10


In [ ]:
print(name)
print(Class)


lisa
10


### PLACEHOLDERS
placeholders are used in strings to insert values dynamically. Placeholders allow variables or expressions to be embedded within strings.

In [ ]:
A="AI"
B=1
C="Wednesday"
print("Course name",A,"session",B,"on",C)
print("Course name %s session %d on %s"%(A,B,C)) # %s- string, %d- integer , %f- float
print(f"Course name {A} session {B} on {C}") # it is avaliable in python 3.6 and above versions
#format
print("Course name {} session {} on {}".format(A,B,C))
print("Course name {0} session {1} on {2}".format(A,B,C))
print("Course name {D} session {E} on {F}".format(D=A,E=B,F=C))

Course name AI session 1 on Wednesday
Course name AI session 1 on Wednesday
Course name AI session 1 on Wednesday
Course name AI session 1 on Wednesday
Course name AI session 1 on Wednesday
Course name AI session 1 on Wednesday


### Comments
for single line use #

for multiple lines use triple quotes '''

In [ ]:
#its for single line
print("single")

'''it is for multiple
lines comment'''

print("multiple line")


single
multiple line


### Data types
<img src="https://media.geeksforgeeks.org/wp-content/uploads/20191023173512/Python-data-structure.jpg" >



### Numeric
<ul>
    <li>integer</li>
    <li>float</li>
    <li>complex number</li>
</ul>

In [ ]:

age=12
print(type(age))

<class 'int'>


In [ ]:
height=156.6
print(type(height))
print("12")

<class 'float'>
12


In [ ]:
complex=15+2j
print(type(complex))


<class 'complex'>


### boolean
in boolean the first letter need to capital

In [ ]:
a=True
print(type(a))
print(10>9)
print(9>10)

<class 'bool'>
True
False


### String

In [ ]:
string="hello world"
print(string)
print(type(string))

hello world
<class 'str'>


### SLICING


### SYNTAX:
### VARIABLE_NAME[start:stop:step]
start: The index to start the slice (inclusive).<br>
stop: The index to stop the slice (exclusive).<br>
step: The interval or step size to use in the slice

<table style="border-collapse: collapse; width: 100%; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2); font-family: Arial, sans-serif;">
    <!-- Positive Indices Row -->
    <tr style="background-color: #d0e2f2;">
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">0</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">1</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">2</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">3</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">4</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">5</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">6</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">7</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">8</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">9</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">10</td>
    </tr>
    <!-- Characters Row -->
    <tr style="background-color: #ffffff;">
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold; font-size: 18px; color: #333;">H</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold; font-size: 18px; color: #333;">E</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold; font-size: 18px; color: #333;">L</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold; font-size: 18px; color: #333;">L</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold; font-size: 18px; color: #333;">O</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd;"></td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold; font-size: 18px; color: #333;">W</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold; font-size: 18px; color: #333;">O</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold; font-size: 18px; color: #333;">R</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold; font-size: 18px; color: #333;">L</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold; font-size: 18px; color: #333;">D</td>
    </tr>
    <!-- Negative Indices Row -->
    <tr style="background-color: #f2d0d0;">
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">-11</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">-10</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">-9</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">-8</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">-7</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">-6</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">-5</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">-4</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">-3</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">-2</td>
        <td style="padding: 10px 15px; text-align: center; border: 1px solid #ddd; font-weight: bold;">-1</td>
    </tr>
</table>


In [ ]:
print(string[0:4]) # hell
print(string[0:11]) # hello world
print(string[6:]) # world
print(string[0:11:2]) # hlowrd
print(string[::2]) # hlowrd
print(string[:7]) # hello w
print(string[::]) # hello world
print(string[-5:-1]) # worl
print(string[-11:]) # hello world
print(string[::-3]) # dooe

hell
hello world
world
hlowrd
hlowrd
hello w
hello world
worl
hello world
dooe


In [ ]:
#Reversing
print(string[::-1])

dlrow olleh


In [ ]:
#concatenation
print(string+"Students")
print(string,"students")

hello worldStudents
hello world students


In [ ]:
#REPEATATION
print("hello "*3)

hello hello hello 


### type casting / type conversion
 Python automatically converts one data type to another. This is known as implicit type conversion.

In [ ]:
item1=6
item2=9.6
item3=item1+item2
print(item3)
print("item1=",item1,type(item1))
print("item2=",item2,type(item2))
print("item3=",item3,type(item3))


15.6
item1= 6 <class 'int'>
item2= 9.6 <class 'float'>
item3= 15.6 <class 'float'>


### Explicit Type Conversion
In Explicit Type Conversion, users convert the data type of an object to required data type.

In [ ]:
item1=6
item2=9.6
item4=item1+int(item2) #6+9=15
print(item4)
print("item4=",item4,type(item4))

15
item4= 15 <class 'int'>


In [ ]:
new=float(input("enter a number"))
#int->float
print("new",new,type(new))
a=10+new
print(a)

enter a number 9


new 9.0 <class 'float'>
19.0


In [ ]:
name="julie"
roll_no=40
print(20+roll_no) #20+40=60
print(type(roll_no)) #int
roll_no=str(40)
print(type(roll_no))
#str
a="20"
print(a+roll_no,type(a+roll_no))
#print(a+40) # error cause we changed the "a" to string value

60
<class 'int'>
<class 'str'>
2040 <class 'str'>


# List
- **Mutable**: Can be modified (elements can be added, removed, or changed).
- **Ordered**: Maintains the insertion order of elements.
- **Indexed**: Elements can be accessed by index (supports slicing).
- **Allows Duplicates**: Can contain duplicate values.
- **Declaration**: `list_variable = [element1, element2, ...]`
- **Common Methods**: `append()`, `extend()`, `insert()`, `remove()`, `pop()`, `sort()`, `reverse()`
- **Data types allowed**: `int,float,str,boolean,nested list,tuple,dictionary,sets,None`

In [ ]:
list1=["hello","world",1.3,100,(2,4),True,{"A":"ME"},None]
print(list1)
print(type(list1))
print(list1[4],type(list1[4]))
list1[1]=0.99
print(list1)
type(list1[-1])

['hello', 'world', 1.3, 100, (2, 4), True, {'A': 'ME'}, None]
<class 'list'>
(2, 4) <class 'tuple'>
['hello', 0.99, 1.3, 100, (2, 4), True, {'A': 'ME'}, None]


NoneType

In [ ]:
#append will add a new element at the end of the list
list1=[1,2,3,4,5]
print(list1)
list1.append(6)
print("after appending 6",list1)

[1, 2, 3, 4, 5]
after appending 6 [1, 2, 3, 4, 5, 6]


In [ ]:
#insert will add a new element in a particular position
# insert(position,value)
list1.insert(2,45)
print("after inserting 3 in the 2nd index",list1)

after inserting 3 in the 2nd index [1, 2, 45, 3, 4, 5, 6]


In [ ]:
#remove will delete the specified element
list1.remove(3)
print("after removing the 3 ",list1)

after removing the 3  [1, 2, 45, 4, 5, 6]


In [ ]:
#The pop() method removes the specified index.If you dont specify the index value it will delete the last element of the list
list1.pop()
print("after poping the last element",list1)
list1.pop(1)
print("after popping the 1st index value",list1)

after poping the last element [1, 2, 45, 4, 5]
after popping the 1st index value [1, 45, 4, 5]


In [ ]:
#sort the values by ascending to descending
unordered=[3,5,2,1,0,9,8,33,209]
print("list2=",unordered)
unordered.sort()
print("after sorting:",unordered)
unordered.reverse()
print("after reversing:",unordered)

list2= [3, 5, 2, 1, 0, 9, 8, 33, 209]
after sorting: [0, 1, 2, 3, 5, 8, 9, 33, 209]
after reversing: [209, 33, 9, 8, 5, 3, 2, 1, 0]


In [ ]:
#slicing
#it is same as string slicing
print("ELEMENTS IN THE LIST",list1)
print(list1[::]) #print all the values
print(list1[:4]) #first 4 values
print(list1[2:4])
print(list1[::2]) #alternative values

ELEMENTS IN THE LIST [1, 45, 4, 5]
[1, 45, 4, 5]
[1, 45, 4, 5]
[4, 5]
[1, 4]


In [ ]:
#extend is used to add a another list into a extending list
list1=[1,2,3,4,5]
list2=["yellow","flower"]
list1.extend(list2)
print("after extending the list:",list1)
print(list2)

after extending the list: [1, 2, 3, 4, 5, 'yellow', 'flower']
['yellow', 'flower']


In [ ]:
#len is used to find the length of the list
print(len(list1))

7


### List Comprehension

List comprehensions offer a concise way to create lists.

Example: Create a list of squares from 0 to 9.


In [ ]:
# List comprehension example
squares = [x**2 for x in range(10)] # range starts from 0 to n-1, here n is 10 so 10-1=9
print("Squares:", squares)            # Output: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


Squares: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
squares[0]=100
print(squares)

[100, 1, 4, 9, 16, 25, 36, 49, 64, 81]


# Set
- **Mutable**: Elements can be added or removed, but individual items cannot be accessed or modified by index.
- **Unordered**: Does not maintain any specific order.
- **No Duplicates**: Automatically removes duplicate values.
- **Unindexed**: Does not support indexing or slicing.
- **Declaration**: `set_variable = {element1, element2, ...}`
- **Data types allowed**: `int,float,str,tuple`

In [ ]:
# Creating a set
fruits = {"apple", "banana", "cherry","mango",1}
print("set:", fruits)
print(type(fruits))

# Creating an empty set

empty_set = set()
empty_set={1,2,3}
print("Empty set:", empty_set)


set: {1, 'banana', 'cherry', 'apple', 'mango'}
<class 'set'>
Empty set: {1, 2, 3}


In [ ]:
# Set operations
fruits.add("orange")
print("After adding 'orange':", fruits)


After adding 'orange': {1, 'banana', 'cherry', 'apple', 'mango', 'orange'}


In [ ]:
fruits.remove("banana")
print("After removing 'banana':", fruits)



After removing 'banana': {1, 'cherry', 'apple', 'mango', 'orange'}


In [ ]:
#update using list
My_list=["kiwi","pineapple"]
fruits.update(My_list)
print("after updating",fruits)

#update using another set
set1={1,2,3}
fruits.update(set1)
print(fruits)

after updating {1, 'pineapple', 'cherry', 'apple', 'mango', 'kiwi', 'orange'}
{1, 2, 3, 'pineapple', 'mango', 'cherry', 'apple', 'kiwi', 'orange'}


In [ ]:
#it is a unindexed so delete a random value
fruits.pop()

1

In [ ]:
#In remove you can specify the value that need to be removed from the set
fruits.remove("pineapple")
print(fruits)

{2, 3, 'mango', 'cherry', 'apple', 'kiwi', 'orange'}


In [ ]:
#union
A = {1, 2, 3}
B = {3, 4, 5}
print(A | B)          # {1, 2, 3, 4, 5}
print(A.union(B))      # {1, 2, 3, 4, 5}


{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5}


In [ ]:
print(A & B)                # {3}
print(A.intersection(B))    # {3}\


{3}
{3}


In [ ]:
print(A - B)               # {1, 2} (elements in A but not in B)
print(A.difference(B))     # {1, 2}


{1, 2}
{1, 2}


In [ ]:
#The symmetric_difference() method will keep only the elements that are NOT present in both sets.
print(A ^ B)                      # {1, 2, 4, 5}
print(A.symmetric_difference(B))  # {1, 2, 4, 5}


{1, 2, 4, 5}
{1, 2, 4, 5}


# Tuple
- **Immutable**: Cannot be modified after creation (elements can’t be added, removed, or changed).
- **Ordered**: Maintains the insertion order of elements.
- **Indexed**: Elements can be accessed by index (supports slicing).
- **Allows Duplicates**: Can contain duplicate values.
- **Declaration**: `tuple_variable = (element1, element2, ...)`
- **Data types allowed**: `int,float,str,dictionary,sets`


In [ ]:
# Tuple creation
numbers = (1, 2, 3, 4)
print("Tuple:", numbers)

# Creating a tuple with one element (requires a comma)
single_element = (5,)
print("Single-element tuple:", single_element)
print(type(single_element))

# Accessing tuple elements
tup = ("apple", "banana", "cherry")
print("First element:", tup[0])
print("Last element:", tup[-1])


Tuple: (1, 2, 3, 4)
Single-element tuple: (5,)
<class 'tuple'>
First element: apple
Last element: cherry


### Example: Tuple Unpacking

You can unpack tuple values into separate variables.


In [ ]:
coordinates = (10.0, 20.0,30)
x, y,z= coordinates
print("Unpacked X:", x)
print("Unpacked Y:", y)
print("Unpacked Z:", z)


Unpacked X: 10.0
Unpacked Y: 20.0
Unpacked Z: 30


# Dictionary
- **Mutable**: Keys and values can be added, removed, or changed.
- **Ordered (since Python 3.7)**: Maintains the insertion order of keys.
- **Key-Value Pairs**: Stores data in key-value pairs, where keys are unique.
- **Keys Must Be Immutable**: Keys can be strings, numbers, or tuples, but not lists or other dictionaries.
- **Declaration**: `dict_variable = {key1: value1, key2: value2, ...}`
- **Data types allowed**: `int,float,str,list,sets`

In [ ]:
# Dictionary creation
person = {
    "name": "Alice",
    "age": 25,
    "city": "New York"
}

# Accessing values
print("Name:", person["name"])
print("Age:", person.get("age"))


Name: Alice
Age: 25


### Common Dictionary Operations

| Operation          | Description                                    | Example                          | Output                |
|--------------------|------------------------------------------------|----------------------------------|------------------------|
| `get()`            | Returns the value for a key                    | `person.get("name")`             | `"Alice"`             |
| `keys()`           | Returns all keys in the dictionary             | `person.keys()`                  | `dict_keys(['name', 'age', 'city'])` |
| `values()`         | Returns all values in the dictionary           | `person.values()`                | `dict_values(['Alice', 25, 'New York'])` |
| `items()`          | Returns all key-value pairs                    | `person.items()`                 | `dict_items([('name', 'Alice'), ('age', 25), ('city', 'New York')])` |
| `update()`         | Updates or adds new key-value pairs            | `person.update({"age": 26})`     | `{'name': 'Alice', 'age': 26, 'city': 'New York'}` |
| `pop()`            | Removes a key and returns its value            | `person.pop("age")`              | `25`                  |
| `clear()`          | Removes all elements from the dictionary       | `person.clear()`                 | `{}`                  |


In [ ]:
# Adding and updating dictionary values
person["job"] = "Engineer" #new key
person["age"] = 30
print("Updated dictionary:", person)



Updated dictionary: {'name': 'Alice', 'age': 30, 'city': 'New York', 'job': 'Engineer'}


In [ ]:
# Dictionary methods
print("Keys:", person.keys())
print("Values:", person.values())
print("Items:", person.items())

Keys: dict_keys(['name', 'age', 'city', 'job'])
Values: dict_values(['Alice', 30, 'New York', 'Engineer'])
Items: dict_items([('name', 'Alice'), ('age', 30), ('city', 'New York'), ('job', 'Engineer')])


In [ ]:
# Removing a key
person.pop("city")

print("After removing 'city':", person)


After removing 'city': {'name': 'Alice', 'age': 30, 'job': 'Engineer'}


## ARITHMETIC OPERATORS

| Operation        | Description   | Example        | Output |
|------------------|---------------|----------------|--------|
| **Addition**     | a + b         | `a + b`        | 13     |
| **Subtraction**  | a - b         | `a - b`        | 7      |
| **Multiplication** | a * b      | `a * b`        | 30     |
| **Division**     | a / b         | `a / b`        | 3.33   |
| **Floor Division** | a // b    | `a // b`       | 3      |
| **Modulus**      | a % b         | `a % b`        | 1      |
| **Exponentiation** | a ** b    | `a ** b`       | 1000   |


In [ ]:
a = 10
b = 3
print("Addition:", a + b)          # 13
print("Subtraction:", a - b)       # 7
print("Multiplication:", a * b)    # 30
print("Division:", a / b)          # 3.33
print("Modulus:", a % b)           # 1
print("Exponentiation:", a ** b)   # 1000
print("Floor Division:", a // b)


Addition: 13
Subtraction: 7
Multiplication: 30
Division: 3.3333333333333335
Modulus: 1
Exponentiation: 1000
Floor Division: 3


   

<h2>Comparison Operators</h2>
<p>These operators compare values and return a Boolean result:</p>
<table border="1" cellpadding="5" cellspacing="0">
    <tr>
        <th>Operator</th>
        <th>Description</th>
        <th>Example</th>
        <th>Output</th>
    </tr>
    <tr>
        <td><code>==</code></td>
        <td>Equal to</td>
        <td><code>10 == 3</code></td>
        <td>False</td>
    </tr>
    <tr>
        <td><code>!=</code></td>
        <td>Not equal to</td>
        <td><code>10 != 3</code></td>
        <td>True</td>
    </tr>
    <tr>
        <td><code>></code></td>
        <td>Greater than</td>
        <td><code>10 > 3</code></td>
        <td>True</td>
    </tr>
    <tr>
        <td><code><</code></td>
        <td>Less than</td>
        <td><code>10 < 3</code></td>
        <td>False</td>
    </tr>
    <tr>
        <td><code>>=</code></td>
        <td>Greater than or equal to</td>
        <td><code>10 >= 3</code></td>
        <td>True</td>
    </tr>
    <tr>
        <td><code><=</code></td>
        <td>Less than or equal to</td>
        <td><code>10 <= 3</code></td>
        <td>False</td>
    </tr>
</table>


In [ ]:
a = 10
b = 20
# Equal to
print(a == b)  # False
# Not equal to
print(a != b)  # True
# Greater than
print(a > b)   # False
# Less than
print(a < b)   # True
# Greater than or equal to
print(a >= b)  # False
# Less than or equal to
print(a <= b)  # True
print(10==10.0)

False
True
False
True
False
True
True


<h2>Logical Operators</h2>
<p>These operators are used to perform logical operations:</p>
<table border="1" cellpadding="5" cellspacing="0">
    <tr>
        <th>Operator</th>
        <th>Description</th>
        <th>Example</th>
        <th>Output</th>
    </tr>
    <tr>
        <td><code>and</code></td>
        <td>Returns True if both statements are true</td>
        <td><code>True and False</code></td>
        <td>False</td>
    </tr>
    <tr>
        <td><code>or</code></td>
        <td>Returns True if at least one statement is true</td>
        <td><code>True or False</code></td>
        <td>True</td>
    </tr>
    <tr>
        <td><code>not</code></td>
        <td>Reverses the result</td>
        <td><code>not True</code></td>
        <td>False</td>
    </tr>
</table>


In [ ]:
a = 5
b = 3
# Using and
print((a > b) and (b > 1))
# Using or
print((a < b) or (b > 1))
# Using not
print(not(a > b))

True
True
False




<h2>Assignment Operators</h2>
<p>These operators are used to assign values to variables:</p>
<table border="1" cellpadding="5" cellspacing="0">
    <tr>
        <th>Operator</th>
        <th>Description</th>
        <th>Example</th>
        <th>Output</th>
    </tr>
    <tr>
        <td><code>=</code></td>
        <td>Assigns a value</td>
        <td><code>x = 10</code></td>
        <td>x is 10</td>
    </tr>
    <tr>
        <td><code>+=</code></td>
        <td>Add and assign</td>
        <td><code>x += 3</code></td>
        <td>x = x + 3</td>
    </tr>
    <tr>
        <td><code>-=</code></td>
        <td>Subtract and assign</td>
        <td><code>x -= 3</code></td>
        <td>x = x - 3</td>
    </tr>
    <tr>
        <td><code>*=</code></td>
        <td>Multiply and assign</td>
        <td><code>x *= 3</code></td>
        <td>x = x * 3</td>
    </tr>
    <tr>
        <td><code>/=</code></td>
        <td>Divide and assign</td>
        <td><code>x /= 3</code></td>
        <td>x = x / 3</td>
    </tr>
    <tr>
        <td><code>%=</code></td>
        <td>Modulus and assign</td>
        <td><code>x %= 3</code></td>
        <td>x = x % 3</td>
    </tr>
    <tr>
        <td><code>//=</code></td>
        <td>Floor divide and assign</td>
        <td><code>x //= 3</code></td>
        <td>x = x // 3</td>
    </tr>
    <tr>
        <td><code>**=</code></td>
        <td>Exponent and assign</td>
        <td><code>x **= 3</code></td>
        <td>x = x ** 3</td>
    </tr>
    <tr>
        <td><code>&=</code></td>
        <td>Bitwise AND and assign</td>
        <td><code>x &= 3</code></td>
        <td>x = x & 3</td>
    </tr>
    <tr>
        <td><code>|=</code></td>
        <td>Bitwise OR and assign</td>
        <td><code>x |= 3</code></td>
        <td>x = x | 3</td>
    </tr>
    <tr>
        <td><code>^=</code></td>
        <td>Bitwise XOR and assign</td>
        <td><code>x ^= 3</code></td>
        <td>x = x ^ 3</td>
    </tr>
    <tr>
        <td><code>&lt;&lt;=</code></td>
        <td>Left shift and assign</td>
        <td><code>x <<= 3</code></td>
        <td>x = x << 3</td>
    </tr>
    <tr>
        <td><code>&gt;&gt;=</code></td>
        <td>Right shift and assign</td>
        <td><code>x >>= 3</code></td>
        <td>x = x >> 3</td>
    </tr>
</table>


In [ ]:
x = 5
x += 3
print(x)
x -= 2
print(x)
x *= 2
print(x)
x /= 4
print(x)


8
6
12
3.0




<h2>Bitwise Operators</h2>
<p>These operators perform bitwise operations on binary numbers:</p>
<table border="1" cellpadding="5" cellspacing="0">
    <tr>
        <th>Operator</th>
        <th>Description</th>
        <th>Example</th>
        <th>Output</th>
    </tr>
    <tr>
        <td><code>&</code></td>
        <td>Bitwise AND</td>
        <td><code>5 & 3</code></td>
        <td>1</td>
    </tr>
    <tr>
        <td><code>|</code></td>
        <td>Bitwise OR</td>
        <td><code>5 | 3</code></td>
        <td>7</td>
    </tr>
    <tr>
        <td><code>^</code></td>
        <td>Bitwise XOR</td>
        <td><code>5 ^ 3</code></td>
        <td>6</td>
    </tr>
    <tr>
        <td><code>~</code></td>
        <td>Bitwise NOT</td>
        <td><code>~5</code></td>
        <td>-6</td>
    </tr>
    <tr>
        <td><code>&lt;&lt;</code></td>
        <td>Bitwise Left Shift</td>
        <td><code>5 &lt;&lt; 1</code></td>
        <td>10</td>
    </tr>
    <tr>
        <td><code>&gt;&gt;</code></td>
        <td>Bitwise Right Shift</td>
        <td><code>5 &gt;&gt; 1</code></td>
        <td>2</td>
    </tr>
</table>


In [ ]:
# Define the variables
a = 5  # Binary: 0000 0101
b = 3  # Binary: 0000 0011

# Bitwise AND
and_result = a & b
print("a & b =", and_result)  # Output: 1

# Bitwise OR
or_result = a | b
print("a | b =", or_result)  # Output: 7

# Bitwise XOR
xor_result = a ^ b
print("a ^ b =", xor_result)  # Output: 6

# Bitwise NOT
not_a = ~a
print("~a =", not_a)  # Output: -6

# Left Shift
left_shift_a = a << 1 #0000 0101 (0000 1010)
print("a << 1 =", left_shift_a)  # Output: 10

# Right Shift
right_shift_a = a >> 1
print("a >> 1 =", right_shift_a)  # Output: 2(0000 0010)



a & b = 1
a | b = 7
a ^ b = 6
~a = -6
a << 1 = 10
a >> 1 = 2




<h2>Membership Operators</h2>
<p>These operators check for the presence of a value in a sequence:</p>
<table border="1" cellpadding="5" cellspacing="0">
    <tr>
        <th>Operator</th>
        <th>Description</th>
        <th>Example</th>
        <th>Output</th>
    </tr>
    <tr>
        <td><code>in</code></td>
        <td>Returns True if the value is present in the sequence</td>
        <td><code>"apple" in fruits</code></td>
        <td>True</td>
    </tr>
    <tr>
        <td><code>not in</code></td>
        <td>Returns True if the value is not present in the sequence</td>
        <td><code>"grape" not in fruits</code></td>
        <td>True</td>
    </tr>
</table>


In [ ]:
# Define a list of fruits
fruits = ["apple", "banana", "cherry"]

# Using the 'in' operator
print("apple" in fruits)     # Output: True
print("grape" in fruits)     # Output: False

# Using the 'not in' operator
print("grape" not in fruits) # Output: True
print("banana" not in fruits) # Output: False


True
False
True
False


### Control Flow Statements: if, if-else, and elif
Key Points<br>
Conditional Statements - Used to execute code based on conditions.<br>
- if: Runs a block of code if a condition is True.
- else: Provides an alternative block of code if the if condition is False.
- elif: Allows for multiple conditions to be checked sequentially.
- Indentation is essential in Python; it defines the code block for each conditional.


In [ ]:
# Example: Check if a number is positive
num = 5
if num > 0:
    print("The number is positive.")


The number is positive.


### if-else Statement
The if-else structure provides an alternative block when the if condition is False.

In [ ]:
# Example: Check if a number is positive or non-positive
num = -3
if num > 0:
    print("The number is positive.")
else:
    print("The number is not positive.")


The number is not positive.


### if-elif-else Statement
The if-elif-else chain is useful when multiple conditions need to be checked.

In [ ]:
# Example: Check if a number is positive, negative, or zero
num = 0
if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")


The number is zero.


### Nested if Statements
Using if statements inside other if statements is called nesting and allows for complex condition checks.

In [ ]:
# Example: Check if a number is positive and even
num = 6
if num > 0:
    if num % 2 == 0:
        print("The number is positive and even.")
    else:
        print("The number is positive and odd.")
else:
    print("The number is not positive.")


The number is positive and even.


In [ ]:
# Example: Check if a number is within a specific range(logical operators)
num = 10
if num > 5 and num < 15:
    print("The number is between 5 and 15.")


The number is between 5 and 15.


### Looping Statements: for and while
Key Points <br>
- Loops allow for repeated execution of a code block.
- for loops iterate over sequences (like lists, tuples, strings) or ranges.
- while loops execute code as long as a condition remains True

In [ ]:
# Example: Print each item in a list
fruits = ["apple", "banana", "cherry"]
for a in fruits:
    print(a)
# Example: Print numbers from 0 to 4
for i in range(5):
    print(i)


apple
banana
cherry
0
1
2
3
4


In [ ]:
# Example: Print numbers from 1 to 5
count = 1
while count <= 5:
    print(count)
    count += 1



1
2
3
4
5


In [ ]:
# Example: Print only even numbers from a list
numbers = [1, 2, 3, 4, 5, 6]
for num in numbers:
    if num % 2 == 0:
        print(num)


2
4
6


### Using break and continue
- break: Immediately exits the loop.
- continue: Skips the rest of the code inside the loop for the current iteration and moves to the next iteration.
- pass: Does nothing; it’s a placeholder for code that hasn’t been written yet.



In [ ]:
# Example: Stop the loop when 'banana' is found
fruits = ["apple",'mango', "banana", "cherry"]
for f in fruits:
    if f == "banana":
        break
    print(f)


apple
mango


In [ ]:
# Example: Skip the number 3
for i in range(5):
    if i == 3:

        continue  # Skip the current iteration
        print("3 is inside if",i)
    print(i,"it is not inside if ")

0 it is not inside if 
1 it is not inside if 
2 it is not inside if 
4 it is not inside if 


In [ ]:
#pass
for i in range(5):
    if i == 3:
        pass  # No action needed for i == 3
    else:
        print(i)

0
1
2
4


In [ ]:
if str(input())==5:
    print("true")

 5


### Functions in Python
#### Key Points
- Functions are reusable blocks of code that perform a specific task.
- Defining a function involves using the def keyword followed by a function name, parameters, and a code block.
- Calling a function runs the code within it.
- Functions help modularize code, making it more organized and manageable.

### Defining and Calling a Basic Function
Functions are defined with the def keyword, followed by the function name and parentheses.


In [ ]:
# Example: Basic greeting function
def greet():
    print("Hello! Welcome to Python.")

# Calling the function
greet()


Hello! Welcome to Python.


### Functions with Parameters
Parameters allow functions to accept input values, making them more flexible.

In [ ]:
# Example: Greeting function with a name parameter
'''syntax
def function_name():
'''
def greet(name):
    print(f"Hello, {name}!")

# Calling the function with an argument
greet("Alice")


Hello, Alice!


### Functions with Multiple Parameters
A function can have multiple parameters to perform more complex tasks.

In [ ]:
# Example: Add two numbers
def add(a, b):
    result = a + b
    print(f"The sum of {a} and {b} is {result}")

# Calling the function
add(3, 5)


The sum of 3 and 5 is 8


### Return Statement
The return statement allows a function to output a value back to the caller, making it useful in calculations and data processing.

In [ ]:
# Example: Function that returns the square of a number
def square(num):
    return num * num

# Storing and printing the result
result = square(4)
print("Square:", result)


Square: 16


### Default Parameters
Default parameters give a default value to parameters, which makes them optional when calling the function.

In [ ]:
# Example: Greet with a default name
def greet(name="Guest"):
    print(f"Hello, {name}!")

# Calling with and without an argument
greet("Alice")
greet()

Hello, Alice!
Hello, Guest!


### Keyword Arguments
Keyword arguments allow you to specify values by parameter names, useful when a function has many parameters.

In [ ]:
# Example: Order function with keyword arguments
def order(item, quantity=1, size="M"):
    print(f"Order: {quantity} {size} {item}(s)")

# Calling with keyword arguments
order(item="T-shirt", size="L", quantity=3)
order("Tie")


Order: 3 L T-shirt(s)
Order: 1 M Tie(s)


### Variable-Length Arguments (*args and **kwargs)
*args: Allows a function to accept multiple positional arguments.<br>
**kwargs: Allows a function to accept multiple keyword arguments.

In [ ]:
# Example: Using *args for a flexible addition function
def add_all(*args):
    return sum(args)

# Calling the function
print("Sum:", add_all(1, 2, 3, 4, 5))

# Example: Using **kwargs for flexible greeting
def introduce(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

# Calling the function
introduce(name="Alice", age=25, city="New York")


Sum: 15
name: Alice
age: 25
city: New York


<h3>LAMBDA FUNCTION</h3>
A lambda function is a small anonymous function.<br>
A lambda function can take any number of arguments, but can only have one expression.



In [ ]:
# Example: Lambda function for adding two numbers
'''syntax
lambda arguments : expression
'''
add = lambda x, y,z:( x + y)-z
print("Sum:", add(3, 5,8))


Sum: 0


## Class
A class defines the attributes (data) and methods (functions) that an object of the class will have. Classes are created using the class keyword.
## Object
An object is an instance of a class created using the class name. Each object has its own set of data and can use the methods defined in the class.
<img src="https://scaler.com/topics/images/class-in-python-1024x858.webp">

In [ ]:
# Defining a class
class system:
    #class variable OR attribute
    brand="HP"
    #class method or function
    def info(self):
        print("hello")

a=system()
print(a.brand)
a.info()


HP
hello


In [ ]:
class Dog:
    # Initializer method/inbuilt constructer
    def __init__(self, name, breed):
        self.name = name      # attribute 'name'
        self.breed = breed # attribute 'breed'

    def __init__(self):
        print("hello")

    # Method to display dog's info
    def bark(self):
        print(f"{self.name} says Woof!")

a=Dog()



hello


#### In this example:

#### Dog is a class.
__init__ is a special method (initializer) that automatically runs when an object is created, setting the initial values of name and breed.
self represents the instance itself and allows access to the instance's attributes and methods.


In [ ]:
class Dog:
    def __init__(self, name, breed):
        self.n = name      # attribute 'n' for name
        self.b = breed     # attribute 'b' for breed

    def bark(self):
        print(f"{self.n} says Woof!")

# Creating objects
dog1 = Dog("Buddy", "Golden Retriever")
dog2 = Dog("Theo", "German Shepherd")

# Accessing attributes and methods
print(dog1.n)     # Output: Buddy
print(dog1.b)     # Output: Golden Retriever
dog1.bark()       # Output: Buddy says Woof!
dog2.bark()       # Output: Theo says Woof!


Buddy
Golden Retriever
Buddy says Woof!
Theo says Woof!


### Inheritance is a feature of object-oriented programming that allows a class (called a child or subclass) to inherit attributes and methods from another class (called a parent or superclass).
#### Types of inheritance
1.Single Inheritance<br>
A child class inherits from one parent class.

In [ ]:
class Parent:
    def greet(self):
        print("Hello from Parent")

class Child(Parent):
    def display(self):
        print("Hello from Child")

obj = Child()
obj.greet()  # Inherited from Parent
obj.display()


Hello from Parent
Hello from Child


#### Multiple Inheritance<br>
A child class inherits from multiple parent classes.

In [ ]:
class Parent1:
    def greet1(self,num):
        self.num=num
        print(f"{self.num} Hello from Parent1")

class Parent2:
    def greet2(self):
        print("Hello from Parent2")

class Child(Parent1, Parent2):
    def greet_child(self):
        print("Hello from Child")

obj = Child()
obj.greet1(2)
obj.greet2()
obj.greet_child()


2 Hello from Parent1
Hello from Parent2
Hello from Child


#### Multilevel Inheritance
A class inherits from a child class, which in turn inherits from another parent class.

In [ ]:
class Grandparent:
    def greet_grandparent(self):
        print("Hello from Grandparent")

class Parent(Grandparent):
    def greet_parent(self):
        print("Hello from Parent")

class Child(Parent):
    def greet_child(self):
        print("Hello from Child")

obj = Child()
obj.greet_grandparent()
obj.greet_parent()
obj.greet_child()


Hello from Grandparent
Hello from Parent
Hello from Child


#### Hierarchical Inheritance
Multiple child classes inherit from a single parent class.


In [ ]:
class Parent:
    def greet(self):
        print("Hello from Parent")

class Child1(Parent):
    def greet_child1(self):
        print("Hello from Child1")

class Child2(Parent):
    def greet_child2(self):
        print("Hello from Child2")

obj1 = Child1()
obj2 = Child2()
obj1.greet()
obj2.greet()


Hello from Parent
Hello from Parent


#### Hybrid Inheritance
A combination of two or more types of inheritance.



## POLYMORPHISM
The word "polymorphism" means "many forms", and in programming it refers to methods/functions/operators with the same name that can be executed on many objects or classes.



In [ ]:
class Car:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Drive!")

class Boat:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Sail!")

class Plane:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Fly!")

car1 = Car("Ford", "Mustang")       #Create a Car class
boat1 = Boat("Ibiza", "Touring 20") #Create a Boat class
plane1 = Plane("Boeing", "747")     #Create a Plane class

for x in (car1, boat1, plane1):
  x.move()


Drive!
Sail!
Fly!


In [ ]:
class Vehicle:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Move!")

class Car(Vehicle):
  pass

class Boat(Vehicle):
  def move(self):
    print("Sail!")

class Plane(Vehicle):
  def move(self):
    print("Fly!")

car1 = Car("Ford", "Mustang") #Create a Car object
boat1 = Boat("Ibiza", "Touring 20") #Create a Boat object
plane1 = Plane("Boeing", "747") #Create a Plane object

for x in (car1, boat1, plane1):
  print(x.brand)
  print(x.model)
  x.move()

Ford
Mustang
Move!
Ibiza
Touring 20
Sail!
Boeing
747
Fly!


## File handling
File handling in Python allows you to read from, write to, and manipulate files stored on your system. The basic operations include opening, reading, writing, and closing files. Here’s a guide to performing these tasks in Python.
<br>"r" – Read (default mode)
<br>"w" – Write (overwrites if the file exists)
<br> "a" – Append (adds to the end of the file if it exists)
<br>"r+" – Read and write
<br> "b" – Binary mode (e.g., "rb" for reading in binary mode)

In [ ]:
import os
print(os.getcwd())


C:\Users\HP


In [ ]:
pwd

'C:\\Users\\HP'

In [ ]:
#varible name=open("filename","mode")
file=open("demo.txt","r")
print(file.read())
print(file)

It is demo file to demonstrate file handling to the students
Hope you guys understand this concept 
BEST OF LUCK!
KEEP LEARNING!
<_io.TextIOWrapper name='demo.txt' mode='r' encoding='cp1252'>


In [ ]:
f=open("C:\\Users\\HP\\OneDrive\\Desktop\\demo.txt","r")
print(f.read())
print(f)

Checking the write function
 It is demo file to demonstrate file handling to the studentsHope you guys understand this conceptBEST OF LUCK!KEEP LEARNING!
<_io.TextIOWrapper name='C:\\Users\\HP\\OneDrive\\Desktop\\demo.txt' mode='r' encoding='cp1252'>


In [ ]:
f=open(r'C:\Users\HP\OneDrive\Desktop\demo.txt',"r")
print(f.readline()) #print 1 line
print(f.read()) # print the rest of the line


Checking the write function

 It is demo file to demonstrate file handling to the studentsHope you guys understand this conceptBEST OF LUCK!KEEP LEARNING!


In [ ]:
f=open(r'C:\Users\HP\OneDrive\Desktop\demo.txt',"w")
f.write("Checking the write function")
f.close()


In [ ]:
f=open(r'C:\Users\HP\OneDrive\Desktop\demo.txt',"r")
print(f.read())
f.close()

Checking the write function


In [ ]:
f=open(r'C:\Users\HP\OneDrive\Desktop\demo.txt',"a")
f.write("\n It is demo file to demonstrate file handling to the students")
f.write("Hope you guys understand this concept")
f.write("BEST OF LUCK!")
f.write("KEEP LEARNING!")
f.close()
f=open(r'C:\Users\HP\OneDrive\Desktop\demo.txt',"r")
print(f.read())

Checking the write function
 It is demo file to demonstrate file handling to the studentsHope you guys understand this conceptBEST OF LUCK!KEEP LEARNING!


## TRY AND ERROR

In [ ]:
# Python code to illustrate
# working of try()
def divide(x, y):
    try:
        # Floor Division : Gives only Fractional Part as Answer
        result = x // y
        print("Yeah ! Your answer is :", result)
    except ZeroDivisionError:
        print("Sorry ! You are dividing by zero ")

# Look at parameters and note the working of Program
divide(3, 0)


Sorry ! You are dividing by zero 


## NUMPY
NumPy (Numerical Python) is a powerful Python library widely used for numerical computations, data analysis, and scientific computing. It provides support for working with arrays and matrices, along with an extensive collection of mathematical functions.

<img src="https://miro.medium.com/v2/resize:fit:720/format:webp/0*p5YOY0e2EXIYHGma.png">

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print("type",type(a))


[1 2 3 4 5]
type <class 'numpy.ndarray'>


In [ ]:
a[0]=10
print("a[0]=",a[0])
print(a)

a[0]= 10
[10  2  3  4  5]


In [ ]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(b)
print(b[0,4])
print(b.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5
(2, 5)


In [ ]:
c=b.reshape(5,2)
print(c)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
print(np.zeros((2, 3)))  # 2x3 array of zeros
print(np.ones((3, 3)))   # 3x3 array of ones
print(np.empty((2, 2)))  # Uninitialized array


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.25 0.5 ]
 [0.75 1.  ]]


In [ ]:
print(np.arange(0, 10, 2))  # Array: [0, 2, 4, 6, 8]
print(np.linspace(0, 1, 5))  # 5 evenly spaced points: [0, 0.25, 0.5, 0.75, 1]

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Element-wise addition
print(a - b)  # Element-wise subtraction
print(a * b)  # Element-wise multiplication
print(a / b)  # Element-wise division


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
arr = np.array([[1, 2], [3, 4]])
print(arr)
print(arr.sum())  # Sum of all elements
print(arr.mean())  # Mean of all elements
print(arr.max())   # Maximum value
print(arr.min())   # Minimum value


[[1 2]
 [3 4]]
10
2.5
4
1


In [ ]:
print(np.random.rand(3))  # 3 random numbers between 0 and 1
print(np.random.randint(1, 10, size=(2, 3)))  # 2x3 random integers from 1 to 10


[0.83274261 0.66747455 0.58889059]
[[8 5 3]
 [3 7 4]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Concatenate along rows (axis=0)
result = np.concatenate((a, b), axis=0)
print(result)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# Concatenate along columns (axis=1)
result = np.concatenate((a, b), axis=1)
print(result)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


<h4>np.vstack() (Vertical Stacking)<br>
Stacks arrays vertically (row-wise). It is equivalent to np.concatenate() with axis=0

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print(result)
# Output:
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


<h4>np.hstack() (Horizontal Stacking) <br>
Stacks arrays horizontally (column-wise). It is equivalent to np.concatenate() with axis=1

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.hstack((a, b))
print(result)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]


[[1 2 5 6]
 [3 4 7 8]]


<h4>Pandas is a Python library widely used for data analysis and manipulation. It provides powerful tools for working with structured data, such as tabular data (like Excel spreadsheets or SQL tables), time series, or hierarchical data.



In [ ]:
import pandas as pd

# Create a Series
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s)

# Accessing values
print(s['a'])  # Output: 10
d=pd.DataFrame(s)
d

a    10
b    20
c    30
d    40
dtype: int64
10


0
a  10
b  20
c  30
d  40

In [ ]:
# Create a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Paris', 'London']}
df = pd.DataFrame(data)
print(df)



      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    London


In [ ]:
data = [
    ["Alice", 25, "New York"],
    ["Bob", 30, "Los Angeles"],
    ["Charlie", 35, "Chicago"]
]
df = pd.DataFrame(data, columns=["Name", "Age", "City"])
print(df)


      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [ ]:
import numpy as np

data = np.array([
    ["Alice", 25, "New York"],
    ["Bob", 30, "Los Angeles"],
    ["Charlie", 35, "Chicago"]
])
df = pd.DataFrame(data, columns=["Name", "Age", "City"])
print(df)


      Name Age         City
0    Alice  25     New York
1      Bob  30  Los Angeles
2  Charlie  35      Chicago


In [ ]:
# Accessing columns
print(df['Name'])  # Output: Series of names


0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object


In [ ]:
# Reading a CSV file
df = pd.read_csv('MARKS.csv')

'''# Reading an Excel file
df = pd.read_excel('data.xlsx')

# Reading from a JSON file
df = pd.read_json('data.json')
'''
df

NAME  CLASS SECTION  SUB 1  SUB 2  Sub 3  TOTAL
0    MARK     12       A     54     56     99    209
1   KEVIN     12       A     99     97    100    296
2   JULIE     12       A     78     67     87    232
3  EDWARD     12       A     56     67     98    221
4    LISA     12       A     98     97     98    293
5  JENNIE     12       A     87     45     56    188
6    JACK     12       A     45     34     78    157
7   JASON     12       A     67     56     98    221

In [ ]:
# Display the first 5 rows
print(df.head())


     NAME  CLASS SECTION  SUB 1  SUB 2  Sub 3  TOTAL
0    MARK     12       A     54     56     99    209
1   KEVIN     12       A     99     97    100    296
2   JULIE     12       A     78     67     87    232
3  EDWARD     12       A     56     67     98    221
4    LISA     12       A     98     97     98    293


In [ ]:
# Display the last 5 rows
print(df.tail())

     NAME  CLASS SECTION  SUB 1  SUB 2  Sub 3  TOTAL
3  EDWARD     12       A     56     67     98    221
4    LISA     12       A     98     97     98    293
5  JENNIE     12       A     87     45     56    188
6    JACK     12       A     45     34     78    157
7   JASON     12       A     67     56     98    221


In [ ]:
# General information about the DataFrame
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   NAME     8 non-null      object
 1   CLASS    8 non-null      int64 
 2   SECTION  8 non-null      object
 3   SUB 1    8 non-null      int64 
 4   SUB 2    8 non-null      int64 
 5   Sub 3    8 non-null      int64 
 6   TOTAL    8 non-null      int64 
dtypes: int64(5), object(2)
memory usage: 580.0+ bytes
None


In [ ]:
# Summary statistics
print(df.describe())

       CLASS      SUB 1      SUB 2       Sub 3       TOTAL
count    8.0   8.000000   8.000000    8.000000    8.000000
mean    12.0  73.000000  64.875000   89.250000  227.125000
std      0.0  20.674346  22.611233   15.480402   47.747663
min     12.0  45.000000  34.000000   56.000000  157.000000
25%     12.0  55.500000  53.250000   84.750000  203.750000
50%     12.0  72.500000  61.500000   98.000000  221.000000
75%     12.0  89.750000  74.500000   98.250000  247.250000
max     12.0  99.000000  97.000000  100.000000  296.000000


In [ ]:
print(df)

     NAME  CLASS SECTION  SUB 1  SUB 2  Sub 3  TOTAL
0    MARK     12       A     54     56     99    209
1   KEVIN     12       A     99     97    100    296
2   JULIE     12       A     78     67     87    232
3  EDWARD     12       A     56     67     98    221
4    LISA     12       A     98     97     98    293
5  JENNIE     12       A     87     45     56    188
6    JACK     12       A     45     34     78    157
7   JASON     12       A     67     56     98    221


In [ ]:
# Filter rows where total > 230
filtered = df[df['TOTAL'] > 230]
print(filtered)


    NAME  CLASS SECTION  SUB 1  SUB 2  Sub 3  TOTAL
1  KEVIN     12       A     99     97    100    296
2  JULIE     12       A     78     67     87    232
4   LISA     12       A     98     97     98    293


In [ ]:
# Add a new column
GENDER = ["M", "M","M","F","F","M", "M","M"]
df['GENDER']=GENDER

# Modify an existing column
df['CLASS'] = df['CLASS'] - 2

df.at[4,'CLASS']=12

df

NAME  CLASS SECTION  SUB 1  SUB 2  Sub 3  TOTAL GENDER
0    MARK     10       A     54     56     99    209      M
1   KEVIN     10       A     99     97    100    296      M
2   JULIE     10       A     78     67     87    232      M
3  EDWARD     10       A     56     67     98    221      F
4    LISA     12       A     98     97     98    293      F
5  JENNIE     10       A     87     45     56    188      M
6    JACK     10       A     45     34     78    157      M
7   JASON     10       A     67     56     98    221      M

In [ ]:
df.loc[6,['SUB 1','SUB 2','Sub 3']]=[85,98,75]
df

NAME  CLASS SECTION  SUB 1  SUB 2  Sub 3  TOTAL GENDER
0    MARK     10       A     54     56     99    209      M
1   KEVIN     10       A     99     97    100    296      M
2   JULIE     10       A     78     67     87    232      M
3  EDWARD     10       A     56     67     98    221      F
4    LISA     12       A     98     97     98    293      F
5  JENNIE     10       A     87     45     56    188      M
6    JACK     10       A     85     98     75    157      M
7   JASON     10       A     67     56     98    221      M

In [ ]:
df.loc[len(df)] = ['Charlie', 10, 'A',35,65,75,175,"M"]
print(df)

      NAME  CLASS SECTION  SUB 1  SUB 2  Sub 3  TOTAL GENDER
0     MARK     10       A     54     56     99    209      M
1    KEVIN     10       A     99     97    100    296      M
2    JULIE     10       A     78     67     87    232      M
3   EDWARD     10       A     56     67     98    221      F
4     LISA     10       A     98     97     98    293      F
5   JENNIE     10       A     87     45     56    188      M
6     JACK     10       A     45     34     78    157      M
7    JASON     10       A     67     56     98    221      M
8  Charlie     10       A     35     65     75    175      M


In [ ]:
# Drop a column
df = df.drop('GENDER', axis=1)

# Drop a row
df = df.drop(8, axis=0)  # Drop row with index 1
print(df)

     NAME  CLASS SECTION  SUB 1  SUB 2  Sub 3  TOTAL
0    MARK     10       A     54     56     99    209
1   KEVIN     10       A     99     97    100    296
2   JULIE     10       A     78     67     87    232
3  EDWARD     10       A     56     67     98    221
4    LISA     10       A     98     97     98    293
5  JENNIE     10       A     87     45     56    188
6    JACK     10       A     45     34     78    157
7   JASON     10       A     67     56     98    221
